### ISSUE TITLE
Display issue with overly wide code

### ISSUE THREAD

**Issue by SingerFlo** [it-at-m/mucgpt#147]
**Describe the bug**
As soon as overly long code is output, it may happen that the display becomes too small. In this case, an additional horizontal scrollbar will appear, making it more difficult to read.

**To Reproduce**
1. Write in your Prompt (several times): "Write a very long code for Powershell."
2. Click Enter

**Expected behavior**
A customized view, essentially a kind of fullscreen mode, to make full use of the width. MUCGPT would need to dynamically adjust to the browser window so that there is only one scrollbar. It may be necessary to fix the header and footer. It would be good if only a vertical scrollbar remained at the end (instead of two).

**Screenshots**
![3-Code-lang](https://github.com/user-attachments/assets/cd36c54e-a149-45ef-82dc-917a5211ac10)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome, edge, firefox

**Comment by Meteord** [comment]
Fixed with https://github.com/it-at-m/mucgpt/pull/218
