### ISSUE TITLE
Version information is not shown

### ISSUE THREAD

**Issue by Meteord** [it-at-m/mucgpt#64]
**Describe the bug**
The version tag is not shown in the frontend:
![grafik](https://github.com/user-attachments/assets/11fca01d-2761-47aa-bf0a-76de90779949)

**To Reproduce**
1. Go to 'settings and feedback drawer'
2. Read 'version settings' 

**Expected behavior**
The correct version tag has to be shown

**Additional context**
The call "\config" doesnt contain the version information

**Comment by pilitz** [comment]
Solved with Pull Request #65
